import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ weight: ['400', '500', '700'], subsets: ["latin"], variable: '--font-inter' });

export const metadata = {
  title: "Shelter Camp",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${inter.variable}`}>
      <head>
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0" />
      </head>
      <body>{children}</body>
    </html>
  );
}
